addEvent("utkozve", true)
addEventHandler("utkozve", root, function(player)
	local x,y,z = getElementVelocity(player) 
	local px, py, pz = getElementPosition(player)
	local playerVehicle = getPedOccupiedVehicle(player)
	setElementVelocity(playerVehicle, 0, 0, 0)
	removePedFromVehicle(player)
	setElementPosition(player, px, py, pz+3)
	setTimer(function()
		setElementHealth(player, 20)
	end, 300, 1)
	setTimer(function()
		setElementFrozen(player, false)
	end, 100, 1000)
	setElementVelocity(player, x*2, y*2, z)
	setElementFrozen(playerVehicle, false)
	
end)